version: '3.1'
services:
  mongo:
    build: ./mongo_replica
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: usuarioAdmin
      MONGO_INITDB_ROOT_PASSWORD: contrasena
      MONGO_INITDB_DATABASE: tasks
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27017:27017'
    volumes:
      - ./mongo:/data/db