"use client";

import { useStore } from '@/store/store'
import { Metadata } from 'next';
import { Grid, Card, CardHeader, IconButton } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import TaskList from '@/components/TaskList/TaskList';
import NewTaskForm from '@/components/NewTaskForm/NewTaskForm';


export const metadata:Metadata = {
  title: 'Home - OpenJira',
  description: 'Generated by Camilo Ordoñez',
}



export default async function Home() {

  return (
    <Grid container spacing={2}>
      <Grid item xs={12} sm={4}>
        <Card sx={{height: 'calc(100vh - 100px)'}}>
          <CardHeader 
          title="To Do"/>
          <NewTaskForm/>
          <TaskList status='pending'/>
        </Card>
      </Grid>
      <Grid item xs={12} sm={4}>
        <Card sx={{height: 'calc(100vh - 100px)'}}>
          <CardHeader 
          title="In Progress"/>
          <TaskList status='in-progress'/>
        </Card>
      </Grid>
      <Grid item xs={12} sm={4}>
        <Card sx={{height: 'calc(100vh - 100px)'}}>
          <CardHeader 
          title="Done"/>
          <TaskList status='finished'/>
        </Card>
      </Grid>
    </Grid>
  )
}
